version: '3.2'

networks:
  e2e-test-net:

services:
  e2e_service:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_CONNECTION=postgresql://postgres:password@db:5432/banking?sslmode=disable
    volumes:
      - $PWD:/go/src
    depends_on:
      db:
        condition: service_healthy
    networks:
      - e2e-test-net