apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: workshop-dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: secret-docker
      containers:
        - name: gopher-api
          image: ghcr.io/dsypasit/workshop:db7721b3367c9bf40ecd7a5276c8f3cb73fd7db0
          imagePullPolicy: Always
          ports:
            - containerPort: 1323
          envFrom:
            - configMapRef:
                name: app-env-config
            - secretRef:
                name: secret-config
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 1323
              httpHeaders:
                - name: Authorization
                  value: "basic YWRtaW46c2VjcmV0"
            initialDelaySeconds: 3
            periodSeconds: 60
