apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: workshop-dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: pun-api
        image: ghcr.io/kkgo-software-engineering/workshop:e6f4cdfde0cbc47fa6381ac0306708b562c1a34a
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api.service.port
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
