apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: workshop-dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      imagePullSecrets:
        - name: docker-secret
      containers:
      - name: pun-api
        image: ghcr.io/kkgo-software-engineering/workshop:697d7c94c6c7d2aa40fdf534abc02ad878c7b19e
        imagePullPolicy: Always
        ports:
        - containerPort: 1323
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api.service.port
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
