apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: workshop-dev
spec:
  selector:
    matchLabels:
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: pun-api
        image: ghcr.io/kkgo-software-engineering/workshop:849efb9190c712589d2118415f4b50e58badb989
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: api.service.port
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
