name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # ==============
  # CI task
  # ==============
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup SHA
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Unit test
        run: make test

      - name: Integration test inside Docker-compose
        run: make test-integration
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/kkgo-software-engineering/workshop:${{ env.GITHUB_SHA }}

      - name: Login ghcr.io
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/kkgo-software-engineering/workshop:${{ env.GITHUB_SHA }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

# ==============
  # CD DEV task
  # ==============
  gitops-dev-versioning:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: change image tag
        run: |
          git --version
          git config user.name "robot"
          git config user.email "root@aorjoa.link"
          sed -i -E "s/ghcr.io\/kkgo-software-engineering\/workshop.*$/ghcr.io\/kkgo-software-engineering\/workshop:${GITHUB_SHA}/" infra/gitops/dev/deployment.yml
          git add infra/gitops/dev/deployment.yml
          git commit -m "[skip actions] 🤖 change dev docker image version to ${GITHUB_SHA}"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repository: kkgo-software-engineering/workshop
          branch: main