name: Dev environment CI and CD

on:
  push:
    branches: [main]
  pull_request:

jobs:
  # ==============
  # CI task
  # ==============
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Setup SHA
        run: echo "GITHUB_SHA=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Unit test
        run: make test-unit

      - name: Integration test inside Docker-compose
        run: make test-integration
      
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/kkgo-software-engineering/workshop:${{ env.GITHUB_SHA }}

      - name: Login ghcr.io
        uses: docker/login-action@v1.8.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true
      
      - name: Push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/kkgo-software-engineering/workshop:${{ env.GITHUB_SHA }}
          # build on feature branches, push only on main branch
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  # ==============
  # CD DEV task
  # ==============
  gitops-dev-versioning:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: config git
        run: |
          git --version
          git config user.name "robot"
          git config user.email "root@aorjoa.link"
        
      - name: change image tag to deploy dev
        run: |
          sed -i -E "s/ghcr.io\/kkgo-software-engineering\/workshop.*$/ghcr.io\/kkgo-software-engineering\/workshop:${GITHUB_SHA}/" infra/gitops/dev/deployment.yml
          git add infra/gitops/dev/deployment.yml
          git commit -m "[skip actions] 🤖 change dev docker image version to ${GITHUB_SHA}"
          git pull --rebase
          git push

      - name: set default docker image tag fot prd
        run: |
          sed -i -E "s/default: .*/default: ${GITHUB_SHA}/" .github/workflows/prd-cd.yaml
          git add .github/workflows/prd-cd.yaml
          git commit -m "[skip actions] 🤖 change default docker tag"
          git pull --rebase
          git push
