name: Prd environment CD

on:
  workflow_dispatch:
    inputs:
      test:
        description: "🔦 QA lead already approved"
        required: true
        type: boolean
      sign-off:
        description: "📝 Make sure PO sign-off"
        required: true
        type: boolean
      deploy-tag:
        description: "🎯 Deploy docker tag"
        required: true
        type: string
        default: db7721b3367c9bf40ecd7a5276c8f3cb73fd7db0

jobs:
  # ==============
  # CD Prd task
  # ==============
  gitops-prd-versioning:
    runs-on: ubuntu-latest
    steps:
      - name: verify manual input
        run: |
          { if [ '${{ inputs.test }}' = 'false' ]; then echo "🔦 QA lead not approve yet"; exit 1; fi }
          { if [ '${{ inputs.sign-off }}' = 'false' ]; then echo "📝 Need PO sign-off"; exit 1; fi }

      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: config git
        run: |
          git --version
          git config user.name "robot"
          git config user.email "root@aorjoa.link"

      - name: change image tag
        run: |
          sed -i -E "s/ghcr.io\/dsypasit\/workshop.*$/ghcr.io\/dsypasit\/workshop:${{ inputs.deploy-tag }}/" infra/gitops/prd/deployment.yml
          git add infra/gitops/prd/deployment.yml
          git commit -m "[skip actions] 🤖 change prd docker image version to ${{ inputs.deploy-tag }}"
          git pull --rebase
          git push
